version: 2.1

orbs:
  python: circleci/heroku@1.2.4

jobs:
  build-and-test:
    executor: circleci/python@3.8.5
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./manage.py test weird_text_app.tests
          name: Test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  main:
    jobs:
      - build-and-test
      - deploy
