version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test weird_text_app.tests
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: "weird-text-app"
      HEROKU_API_KEY: "0fdb1c63-bbae-4741-92e1-b33fed9d8ed6"
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
