version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./manage.py test weird_text_app.tests
          name: Test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  main:
    jobs:
      - build-and-test
      - deploy
